### ISSUE TITLE
Homepage does not communicate well

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#803] opened 2017-05-26 16:59 UTC
We have really high bounce rate on the homepage. In my opinion, and when speaking to a designer, we don't communicate _what_ quran.com does. For example, Airbnb tells you what they do and gives you the tools to customize your experience (search, etc).

![image](https://cloud.githubusercontent.com/assets/3749095/26504555/4618138e-4202-11e7-9ce3-ada6b6eb3aaf.png)

Meanwhile, we took legacy.quran.com and made it look nicer. Thoughts around concepts we can do for the homepage? Ideally, we'd A/B test it

**Comment by mmahalwy** [comment] 2017-05-26 17:04
To begin, what I will do is transform our homepage into sketch so we can have people contribute on the design

- [ ] Create the design in sketch

**Comment by m-adilshaikh** [comment] 2017-05-28 18:46
@mmahalwy will it go on invision? I don't have MacOS but I want to contribute, perhaps I could contribute there. If so, can I get an invite?

**Comment by sabeurthabti** [comment] 2017-05-29 13:40
@m-adilshaikh We use zeplin.

**Comment by mmahalwy** [comment] 2017-05-30 18:45
Sure +1 to both.

**Comment by naveed-ahmad** [comment] 2017-05-30 19:13
Sadly can't contribute in UI but as a user I would love to have these features on home page:

- When I visit Quran.com first time, app show me a welcome dialog, ask for login etc. Then guide me how to use app, something like this http://heelhook.github.io/chardin.js/
- Progress bar for each surah( a progress bar or text showing how many ayah I've read/listened for each surah ) 
- Lets bring the "continue" feature back with improvements 
- Tabs on home page:
  - Default tab would be current surah listing
  - Then list surah by juzz/Para name ( in Pakistan )
  - Verse related to topic/theme. quranindex.info/topics We've data and permission

**Comment by mmahalwy** [comment] 2017-05-30 21:38
@naveed-ahmad awesome suggestions! I think we definitely need to make auth work. one.quran.com has been stagnated and we should work on it again to make it work

**Comment by alirobe** [comment] 2017-07-06 08:24
I would suggest that there are many really good designers, who would love to contribute to this effort to "increase conversion" (so much more appropriate in this context than most websites I deal with!)... But they aren't likely to be on Github. :)

I've sent a tweet to http://gould.sydney/ referring him to this issue, perhaps if anyone else knows good designers who could help pro-bono, they could also reach out on behance, twitter, etc?

**Comment by mmahalwy** [comment] 2017-07-07 06:51
Thanks @alirobe for tweeting that out! We do need designers, you are right. I can take a look at Dribbble

**Comment by yazinsai** [comment] 2017-08-07 08:53
A good place to start would be to analyze the incoming search traffic. Where is it coming from? What are people expecting to see? If you can share an export from GA, I'm happy to sift through it and kick this process off.

Big picture, I would suggest something like this:
- Figure out why people are visiting the site in the first place
  - Google Analytics report breakdown (organic vs. referral)
  - Find out what 80% of people are searching for -- this is the optimization goal (i.e. apply the Pareto principle to the incoming traffic)
- Optimize for the 80% use-case 
  - Set conversion goal (e.g. specific sura/ayah is "read", verse recording is played, etc.)
  - A/B test designs
  - Pick winner

Thoughts?

**Comment by imadmk** [comment] 2017-08-24 00:48
@m-adilshaikh 
Maybe we can use [Invision Inspect|https://www.invisionapp.com/feature/inspect] too. Great tool i found besides zeplin.
And you can join the chat on https://quranslack.herokuapp.com

**Comment by alirobe** [comment] 2017-08-24 09:08
Just in terms of observing interactions and iterative design improvements, I've found www.hotjar.com to be very helpful.

**Comment by mmahalwy** [comment] 2017-08-25 22:09
@yazinsai I can certainly add you to the Google Analytics account. Ultimately, it would be great to democratize all the data/analytics we have for Quran.com for anyone to help and contribute. Need to figure out the best way to do that.

@alirobe agreed! hotjar could get expensive if no one is watching and paying attention to them. Let's add Google Tag Manager first and it will allow us to easily add and remove tools like this?

**Comment by yazinsai** [comment] 2017-08-30 11:08
@mmahalwy yes, please! I'm yazin87 [at] gmail

**Comment by mmahalwy** [comment] 2017-12-13 06:47
Salam all, wanted to resurface this. Would be great to get thoughts!

**Comment by m-adilshaikh** [comment] 2017-12-16 17:12
@mmahalwy Any insights to better understand the cause? If there is some activity before bounce, heatmaps etc could help

**Comment by mmahalwy** [comment] 2017-12-17 17:27
@m-adilshaikh happy to dig up anything you'd like!

**Comment by UmanShahzad** [comment] 2017-12-22 20:08
It'd be interesting to compare bouncing on a site like this to 'bouncing' away from a real Qur'an? What're the main use cases of Quran.com? If it's to read the Qur'an, then this comparison would be useful -- what normally turns a person off from reading? Although that question is broad and might be quite out of scope ;p

I do think, though, that implementing user accounts would be a strong way to attach people to the site. It's hard to reflect on where you are with the Qur'an unless there's some kind of easy-to-retrieve record, whether that be in your head or on a site with bookmarks and what not. When you know that you're *here* or *there* on *that site*, you go to check it. tl;dr move forward with one.quran.com?

**Comment by mmahalwy** [comment] 2017-12-25 20:41
@UmanShahzad I agree. I think we should revive one.quran.com

**Comment by Ammaar** [comment] 2018-03-15 13:00
Salaam - I came back to Quran.com after several months ... didn't it used to have a login feature that allowed bookmarking and saving settings? I tried searching for update/release logs for why it was removed but couldn't find anything. Would like to have it back!

**Closed** 2018-08-30 16:28 UTC
Labels: Discussion, enhancement, feature
