### ISSUE TITLE
Play button is not working when ...

### ISSUE THREAD

**Issue by mahfuzul** [quran/quran.com-frontend#587] opened 2017-01-17 14:07 UTC
Play button is not working when we load a surah by pressing "Next Surah" or "Previous Surah" button in the footer.

OS: Linux
Browser: Chrome Version 55.0.2883.87 (64-bit)

**Comment by aigyz** [comment] 2017-01-17 19:50
Hi @mahfuzul, I am also on Linux, browser is the same.
It is working for me.
Can you disable all extensions and look Chrome's console?
Thanks

**Comment by umairidris** [comment] 2017-01-19 06:00
I am not able to reproduce this either (Chrome, Ubuntu Gnome 16.04). 

Though I did encounter a strange bug where using the next surah button turns on all translations. This seems to be fixed in staging though so not worth to open an issue for this. I would follow @aigyz advice and use a fresh browser instance (you can add a new user so you don't need to manually disable each extension).

**Comment by sabeurthabti** [comment] 2017-04-25 21:21
closing as this is not reproducible

**Closed by sabeurthabti** 2017-04-25 21:21 UTC
