### ISSUE TITLE
Audio plays ayah 2 from the end

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#603] opened 2017-01-20 07:41 UTC
STR:
- Go to surah 67.
- Click the 'Play ayah' on the first ayah
- Wait for it to finish
- When playing second ayah, it plays it from the end. This might be due to the first ayah audio is shorter and the time is not updated.

**Comment by umairidris** [comment] 2017-01-20 08:02
Duplicate of #566

**Closed** 2017-01-20 19:08 UTC
