### ISSUE TITLE
Audio playing error: Workaround to Adblock browser extension?

### ISSUE THREAD

**Issue by aa7955** [quran/quran.com-frontend#846] opened 2017-07-14 22:12 UTC
Get the following error when trying to play a verse in Chrome 59.0.3071.115

<img width="388" alt="screen shot 2017-07-14 at 3 10 15 pm" src="https://user-images.githubusercontent.com/6264696/28232641-b37b97b4-68a6-11e7-9cd2-aedd43e10422.png">

**Comment by mmahalwy** [comment] 2017-07-14 22:12
Staging or production?

**Comment by ajalger** [comment] 2017-07-14 22:13
Production

**Comment by ajalger** [comment] 2017-07-14 22:19
So, the issue is with Adblock Plus. If you have Adblock Plus installed, then it will block the audio files. I haven't seen this before on other sites, but if I am having this issue, I am sure others are as well. Perhaps there is a workaround to this.

**Comment by mmahalwy** [comment] 2017-07-21 00:26
@ahmedre ^^

**Comment by ahmedre** [comment] 2017-07-21 11:21
can you run the javascript console and add the error message you're getting when you try to play using Adblock Plus so that we can know where the actual issue is?

**Comment by mmahalwy** [comment] 2017-07-21 17:29
We could definitely do that! Let's add that ask an issue

**Comment by ajalger** [comment] 2017-07-28 04:27
@ahmedre the first issue is what the JavaScript console produces.

**Comment by bahaa96** [comment] 2018-07-20 16:04
Is this Issue still open ?? 
I've installed Adblock plus and it's working like charm. Either on staging or production.

**Comment by aa7955** [comment] 2018-07-20 16:23
if it's fixed, just close it then.

**Comment by bahaa96** [comment] 2018-07-20 16:57
Would you matter to check it now ?

**Comment by aa7955** [comment] 2018-07-20 17:02
Trying to play Surah al-Fatiha ...

Same issue running on Chrome:
```
raven.min.js:2 Audioplayer mounted but no file available
a.(anonymous function) @ raven.min.js:2
```
Firefox has the same errors. Here's something extra:

<img width="1117" alt="screen shot 2018-07-20 at 10 00 50 am" src="https://user-images.githubusercontent.com/6264696/43015230-e04ab12c-8c03-11e8-9d2e-dd201f3824e5.png">

**Comment by naveed-ahmad** [comment] 2018-07-20 21:45
Salam brothers, I'm closing this. Issue have been fixed, but staging build are failing. Preparing for production build, and need to clear the fixed issues. They're scary :)

**Closed by naveed-ahmad** 2018-07-20 21:45 UTC
